data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'DLHLP'                   # Specify corpus
    path: 'D:/NTU ASR/DLHLP'
    train_split: ['D:/NTU ASR/DLHLP/train'] # Official LM src from LibriSpeech
    dev_split: ['D:/NTU ASR/DLHLP/dev']
    bucketing: True
    batch_size: 32
  text:
    mode: 'character'                     # 'character'/'word'/'subword'
    vocab_file: 'D:/NTU ASR/DLHLP/bopomo_vocab_file'

hparas:                                   # Experiment hyper-parameters
  valid_step: 10000
  max_step: 100000000
  optimizer: 'Adam'
  lr: 0.0001
  eps: 0.00000001
  lr_scheduler: 'fixed'                    # 'fixed'/'warmup'
  
model:                                     # Model architecture
  emb_tying: False                         # https://arxiv.org/pdf/1608.05859.pdf
  emb_dim: 1024
  module: 'LSTM'                           # 'LSTM'/'GRU'
  dim: 1024
  n_layers: 2
  dropout: 0.5
  
  
